# Generated by Django 3.2.23 on 2024-08-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_auto_20240322_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
