# Generated by Django 3.2.23 on 2024-08-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_producttype_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField()),
                ('registered', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
    ]
