# Generated by Django 3.2.23 on 2024-08-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_deviceinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashierdynamicproducts',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expense',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scannedproductheader',
            name='change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='scannedproductheader',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scannedproducts',
            name='summed_product_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='soldoutproduct',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='total_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='totalexpenses',
            name='expense',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='totalincome',
            name='income',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='totalrevenue',
            name='revenue',
            field=models.FloatField(default=0),
        ),
    ]
