# Generated by Django 3.2.23 on 2024-08-28 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0028_auto_20240815_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='refunded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='refunded_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='refunded_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soldproducts',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soldproducts',
            name='refunded_cash',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='soldproducts',
            name='refunded_change',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='soldproducts',
            name='refunded_total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='cash',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='change',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('change', models.FloatField(default=0.0)),
                ('cash', models.FloatField(default=0.0)),
                ('date_refunded', models.DateTimeField()),
                ('date_time_refunded', models.DateField()),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(to='management.SoldProduct')),
            ],
        ),
    ]
